server:
  port: 8080

tag:
  version: ${VERSION}

chatflow:
  http-url: ${CHATFLOW_HTTP_URL}
  https-url: ${CHATFLOW_HTTPS_URL}

spring:
  application:
    name: chat
  profiles:
    active: ${PROFILE_ACTIVE}
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      #      maximum-pool-size: 5
      #      minimum-idle: 2
      #      idle-timeout: 200000            # 유휴 커넥션 닫는 시간 (keepalive-time 설정시 무시됨)
      max-lifetime: 40000             # 커넥션 재생성 시점 (DB보다 짧게)
    #      keepalive-time: 30000           # ping 주기
    #      connection-timeout: 10000       # 커넥션 획득 대기 시간 줄이기
    #      validation-timeout: 5000        # 커넥션 유효성 검사 timeout
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  kafka:
    bootstrap-servers: "kafka-controller-headless.kafka.svc.cluster.local:9092"
    properties:
      security.protocol: PLAINTEXT # ???? ??
      bootstrap.servers.protocol.map: CLIENT:PLAINTEXT
      client.id: "notification-kafka-client" # ????? ID ??
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
    consumer:
      group-id: "notification-service-group"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      isolation-level: read_committed
    #      enable-auto-commit: true
  #    streams:
  #      application-id: "team-streams-app"
  #      processing.guarantee: exactly_once_v2
  #      properties:
  #        commit.interval.ms: 100

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /notification/swagger
    display-request-duration: true
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /notification/v3/api-docs
    groups:
      enabled: true

jwt:
  secret-key: user_token_for_signature_must_be_at_least_256_bits_in_HMAC_signature_algorithms